/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ResearchApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ResearchData": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Site": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}