/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* biome-ignore-all lint: auto-generated */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_API_URL: string
  readonly VITE_CHAT_URL: string
  readonly VITE_RESEARCH_URL: string
  readonly VITE_AGENT_RUNNER_URL: string
  readonly VITE_AUTH_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}